### ISSUE TITLE
HTTP headers are not printed in a consistent order

### ISSUE THREAD

**Issue by zedkipp** [andboson/http-echo-logger#13]
Seems like HTTP headers are not printed in a consistent order through the CLI and the web interface. This is kind of annoying when trying to view multiple requests to the same endpoint.

Picture of this in the web interface: https://imgur.com/MjSYvQz

GIF of this happening in the CLI:  https://imgur.com/CBQOtZN

From my knowledge of Go, I'd guess this is map behavior causing this.

**Comment by andboson** [comment]
Hello Zacho2!
Thanks for noticing that
I'll take a look

**Comment by andboson** [comment]
Fixed - saved headers order in the history and CLI.
But yeah, you are right - headers in Go are stored as a map. So, there is no guaranty the order will be the same on every request.
